spring:
  profiles:
    active: prod
  application:
    name: ekart-api-gateway
        # name: eKartApiGateway
  cloud:
    gateway:
          discovery:
            locator:
              enabled: true

#          globalcors:
#            corsConfigurations:
#              '[/**]':
#                allowedOrigins:
#                  - "http://localhost:3000"
#                allowedMethods:
#                  - GET
#                  - POST
#                  - PUT
#                  - DELETE
#                  - OPTIONS
#                allowedHeaders:
#                  - "*"
#                allowCredentials: true
#                maxAge: 3600

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_SERVER_HOSTNAME:localhost}:8761/eureka/


jwt:
  secretkey: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

server:
  port: 8080
