spring:
  application:
    name: api-gateway
    # name: eKartApiGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

jwt:
  secretkey: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

server:
  port: 8080

#logging:
#  level:
#    java.lang.UnsatisfiedLinkError:
