services:
  - type: web
    name: ekart-api-gateway
    env: docker
    branch: main
    region: oregon
    rootDir: backend/eKartApiGateway
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      # Add DB vars only if needed here

  - type: web
    name: ekart-config-server
    env: docker
    branch: main
    region: oregon
    rootDir: backend/eKartConfigServer
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: web
    name: ekart-eureka-server
    env: docker
    branch: main
    region: oregon
    rootDir: backend/eKartEurekaServer
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: web
    name: ekart-image-upload-service
    env: docker
    branch: main
    region: oregon
    rootDir: backend/eKartImageUploadService
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: web
    name: ekart-order-service
    env: docker
    branch: main
    region: oregon
    rootDir: backend/eKartOrderService
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d0kueeogjchc73el9a3g-a.oregon-postgres.render.com:5432/ekartdb_rz47
      - key: SPRING_DATASOURCE_USERNAME
        value: ekart
      - key: SPRING_DATASOURCE_PASSWORD
        value: zATZzIfUryHlusKi5hbWjkez2ttFOWBO

  - type: web
    name: ekart-payment-service
    env: docker
    branch: main
    region: oregon
    rootDir: backend/eKartPaymentService
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d0kueeogjchc73el9a3g-a.oregon-postgres.render.com:5432/ekartdb_rz47
      - key: SPRING_DATASOURCE_USERNAME
        value: ekart
      - key: SPRING_DATASOURCE_PASSWORD
        value: zATZzIfUryHlusKi5hbWjkez2ttFOWBO

  - type: web
    name: ekart-product-service
    env: docker
    branch: main
    region: oregon
    rootDir: backend/eKartProductService
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d0kueeogjchc73el9a3g-a.oregon-postgres.render.com:5432/ekartdb_rz47
      - key: SPRING_DATASOURCE_USERNAME
        value: ekart
      - key: SPRING_DATASOURCE_PASSWORD
        value: zATZzIfUryHlusKi5hbWjkez2ttFOWBO

  - type: web
    name: ekart-user-auth-service
    env: docker
    branch: main
    region: oregon
    rootDir: backend/eKartUserAuthService
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d0kueeogjchc73el9a3g-a.oregon-postgres.render.com:5432/ekartdb_rz47
      - key: SPRING_DATASOURCE_USERNAME
        value: ekart
      - key: SPRING_DATASOURCE_PASSWORD
        value: zATZzIfUryHlusKi5hbWjkez2ttFOWBO
