server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: prod

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${RENDER_EXTERNAL_HOSTNAME:localhost}}
    prefer-ip-address: true
