server:
  port: 8888

spring:
  profiles:
    active: prod
  cloud:
    config:
          server:
            git:
              uri: https://github.com/rajneesh11/demo-git-config-server
              # optionally:
              # username: your-username
              # password: your-password

