spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://ekart:zATZzIfUryHlusKi5hbWjkez2ttFOWBO@dpg-d0kueeogjchc73el9a3g-a/ekartdb_rz47
#    url: jdbc:postgresql://localhost:5432/ekart
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: prod

jwt:
  secretkey: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

server:
  port: 8081

