spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ekart
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secretkey: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

server:
  port: 8081
