spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ekartdb
    driver-class-name: org.postgresql.Driver
    username: ekart
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: prod

jwt:
  secretkey: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

server:
  port: 8081

