# NOTE: This configuration is for DEV/STAGING environment on Render

server:
  port: 0

spring:
  application:
    name: ekart-product-service

  config:
    import: optional:configserver:http://ekart-config-server.onrender.com

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://ekart-eureka-server.onrender.com/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
